apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service

spec:
  type: NodePort

  selector:
    app: fraud-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080